---

- name: install the common packages
  yum: name={{ item }} state=present
  with_items:
    - ntp
    - sysstat
    - gcc
    - gcc-c++
    - cmake
    - automake
    - openssl
    - openssl-devel
    - glibc-common

- name: disabled selinux
  selinux: state=disabled

- name: disabled non-common service
  service: name={{ item }} state=stopped enabled=no
  with_items:
    - acpid
    - avahi-daemon
    - avahi-dnsconfd
    - bluetooth
    - hidd
    - atd
    - firstboot
    - gpm
    - ip6tables
    - isdn
    - kudzu
    - mdmonitor
    - netfs
    - nfslock
    - pcscd
    - portmap
    - restorecond
    - rpcgssd
    - rpcidmapd
    - sendmail
    - vsftpd
    - NetworkManager
    - iscsi
    - iscsid
    - mcstrans
    - NetworkManager

- name: ensure the service start
  service: name={{ item }} state=started enabled=yes
  with_items:
    - anacron 
    - crond 
    - haldaemon 
    - irqbalance 
    - microcode_
    - ctl 
    - messagebus 
    - network 
    - ntpd 
    - sshd 
    - syslog 
    - sysstat

- name: create the backup repo directory
  file: dest=/etc/yum.repos.d/bak state=directory

- name: mv the old repo
  shell: mv /etc/yum.repos.d/CentOS-* /etc/yum.repos.d/bak

- name: download 163 repo
  get_url: url=http://mirrors.163.com/.help/CentOS5-Base-163.repo dest=/etc/yum.repos.d/ force=yes

- name: install epel
  shell: rpm -Uvh ftp://mirrors.ustc.edu.cn/fedora/epel/5/x86_64/epel-release-5-4.noarch.rpm
  notify: yum makecache
    
- name: utpdate time
  cron: job="/usr/sbin/ntpdate ntp.fudan.edu.cn >/dev/null 2>&1" minute="*/4"

- name: ulimit
  shell: echo -e "* soft nofile 65536\n* hard nofile 65536i\n" >> /etc/security/limits.conf

- name: modify sysctl.conf
  sysctl: name=vm.swappiness value=10 state=present

- name: sysctl.conf
  sysctl: name=vm.vfs_cache_pressure value=200 state=present

- name: disabled ctrl+alt+del
  shell: sed -i "s/ca::ctrlaltdel:\/sbin\/shutdown\ -t3\ -r\ now/#ca::ctrlaltdel:\/sbin\/shutdown\ -t3\ -r\ now/" /etc/inittab

- name: disable ipv6
  shell: echo "alias net-pf-10 off" >> /etc/modprobe.conf ; echo "alias ipv6 off" >> /etc/modprobe.conf ;sed -ir 's/NETWORKING_IPV6=.*/NETWORKING_IPV6=no/g' /etc/sysconfig/network

